"""Plot CPU core-utilization timeline from worker CPU sampler output."""

from __future__ import annotations

import argparse
import csv
import json
import re
from collections import defaultdict
from dataclasses import dataclass
from datetime import datetime, timedelta
from pathlib import Path

import matplotlib.dates as mdates
import matplotlib.pyplot as plt
import numpy as np

ISO_FORMAT = "%Y-%m-%d %H:%M:%S.%f"


@dataclass(frozen=True)
class PhaseWindow:
    name: str
    start: datetime
    end: datetime
    source: str


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("run_dir", type=Path, help="Profile run directory.")
    parser.add_argument(
        "--output-prefix",
        type=Path,
        default=None,
        help="Output prefix. Defaults to <run_dir>/cpu/cpu_core_util_timeline.",
    )
    parser.add_argument(
        "--smooth-window-s",
        type=float,
        default=30.0,
        help="Centered moving average window in seconds.",
    )
    parser.add_argument(
        "--x-pad-s",
        type=float,
        default=90.0,
        help="Extra x-axis padding in seconds on both sides.",
    )
    parser.add_argument(
        "--bin-s",
        type=float,
        default=1.0,
        help="Aggregation bin size in seconds for per-core utilization.",
    )
    parser.add_argument(
        "--cache-prefix",
        type=Path,
        default=None,
        help="Cache prefix. Defaults to <run_dir>/cpu/cpu_core_util_agg_<bin>s.",
    )
    parser.add_argument(
        "--phase-csv",
        type=Path,
        default=None,
        help="Phase CSV generated by the GPU timeline script. Defaults to the latest GPU phase CSV.",
    )
    parser.add_argument(
        "--rebuild-cache",
        action="store_true",
        help="Rebuild cached aggregated CPU CSVs even if they already exist.",
    )
    return parser.parse_args()


def iter_jsonl(path: Path) -> list[dict]:
    records = []
    with path.open() as handle:
        for line in handle:
            line = line.strip()
            if line:
                records.append(json.loads(line))
    return records


def ns_to_datetime(wall_ns: int) -> datetime:
    return datetime.fromtimestamp(wall_ns / 1_000_000_000)


def read_rollout_window(run_dir: Path) -> PhaseWindow:
    starts: list[datetime] = []
    ends: list[datetime] = []
    for timestamp_dir in [
        run_dir / "logs" / "rollout_generation_timestamps",
        run_dir / "logs" / "env_sim_timestamps",
    ]:
        for path in sorted(timestamp_dir.glob("*.jsonl")):
            for record in iter_jsonl(path):
                if "wall_ns" not in record:
                    continue
                dt = ns_to_datetime(int(record["wall_ns"]))
                if record.get("event") == "start":
                    starts.append(dt)
                elif record.get("event") == "end":
                    ends.append(dt)
    if not starts or not ends:
        raise ValueError(f"Could not infer rollout window under {run_dir}/logs")
    return PhaseWindow(
        name="Rollout",
        start=min(starts),
        end=max(ends),
        source="logs/rollout_generation_timestamps + logs/env_sim_timestamps",
    )


def read_actor_training_seconds(train_log: Path) -> float | None:
    if not train_log.exists():
        return None
    match = re.search(r"actor/run_training=([0-9.]+)", train_log.read_text(errors="ignore"))
    return float(match.group(1)) if match else None


def parse_datetime(value: str) -> datetime:
    for fmt in (ISO_FORMAT, "%Y-%m-%d %H:%M:%S"):
        try:
            return datetime.strptime(value, fmt)
        except ValueError:
            continue
    raise ValueError(f"Unsupported datetime format: {value}")


def read_phase_csv(path: Path) -> list[PhaseWindow]:
    phases = []
    with path.open(newline="") as handle:
        reader = csv.DictReader(handle)
        for row in reader:
            phases.append(
                PhaseWindow(
                    name=row["phase"],
                    start=parse_datetime(row["start"]),
                    end=parse_datetime(row["end"]),
                    source=row.get("source", str(path)),
                )
            )
    return phases


def find_default_phase_csv(run_dir: Path) -> Path | None:
    gpu_dir = run_dir / "gpu"
    preferred = [
        gpu_dir
        / "gpu_util_rollout_train_timeline_wallclock_smooth30s_p90_nomlegend_nobg_noticks_5min_xpad90s_rollout_note_phases.csv",
        gpu_dir / "gpu_util_rollout_train_timeline_phases.csv",
    ]
    for path in preferred:
        if path.exists():
            return path
    candidates = sorted(gpu_dir.glob("*phases.csv"), key=lambda path: path.stat().st_mtime)
    return candidates[-1] if candidates else None


def infer_train_window(
    times: np.ndarray,
    p90_util: np.ndarray,
    rollout_end: datetime,
    training_seconds: float | None,
) -> PhaseWindow | None:
    active = p90_util >= 20.0
    start: datetime | None = None
    end: datetime | None = None
    for timestamp_s, is_active in zip(times, active, strict=True):
        timestamp = datetime.fromtimestamp(float(timestamp_s))
        if timestamp <= rollout_end:
            continue
        if is_active:
            if start is None:
                start = timestamp
            end = timestamp
        elif start is not None and end is not None:
            if (end - start).total_seconds() >= 5.0:
                break
            start = None
            end = None
    if start is None or end is None:
        return None
    if training_seconds is not None:
        end = start + timedelta(seconds=training_seconds)
    return PhaseWindow(
        name="Train",
        start=start,
        end=end,
        source="post-rollout CPU p90 activity + train.log actor/run_training",
    )


def cache_paths(cache_prefix: Path) -> tuple[Path, Path]:
    return (
        cache_prefix.with_name(cache_prefix.name + "_summary.csv"),
        cache_prefix.with_name(cache_prefix.name + "_per_core.csv"),
    )


def build_cpu_core_cache(
    raw_path: Path,
    cache_prefix: Path,
    bin_s: float,
) -> tuple[Path, Path]:
    by_time_core: dict[tuple[float, int], list[float]] = defaultdict(lambda: [0.0, 0.0])
    with raw_path.open(newline="") as handle:
        reader = csv.DictReader(handle)
        for row in reader:
            try:
                raw_timestamp = float(row["timestamp"])
                timestamp = round(round(raw_timestamp / bin_s) * bin_s, 6)
                core = int(row["cpu"])
                active_pct = float(row["active_pct"])
            except (KeyError, ValueError):
                continue
            aggregate = by_time_core[(timestamp, core)]
            aggregate[0] += active_pct
            aggregate[1] += 1.0

    by_time: dict[float, list[float]] = defaultdict(list)
    summary_path, per_core_path = cache_paths(cache_prefix)
    summary_path.parent.mkdir(parents=True, exist_ok=True)
    with per_core_path.open("w", newline="") as handle:
        writer = csv.DictWriter(
            handle, fieldnames=["timestamp", "datetime", "cpu", "active_pct"]
        )
        writer.writeheader()
        for (timestamp, core), (total, count) in sorted(by_time_core.items()):
            active_pct = total / count if count else 0.0
            by_time[timestamp].append(active_pct)
            writer.writerow(
                {
                    "timestamp": f"{timestamp:.6f}",
                    "datetime": datetime.fromtimestamp(timestamp).strftime(ISO_FORMAT)[:-3],
                    "cpu": core,
                    "active_pct": f"{active_pct:.6f}",
                }
            )

    times = np.array(sorted(by_time), dtype=float)
    with summary_path.open("w", newline="") as handle:
        writer = csv.DictWriter(
            handle,
            fieldnames=["timestamp", "datetime", "mean", "p90", "max", "core_count"],
        )
        writer.writeheader()
        for timestamp in times:
            values = by_time[timestamp]
            writer.writerow(
                {
                    "timestamp": f"{timestamp:.6f}",
                    "datetime": datetime.fromtimestamp(timestamp).strftime(ISO_FORMAT)[:-3],
                    "mean": f"{np.mean(values):.6f}",
                    "p90": f"{np.quantile(values, 0.9):.6f}",
                    "max": f"{np.max(values):.6f}",
                    "core_count": len(values),
                }
            )
    return summary_path, per_core_path


def read_cpu_core_series(
    raw_path: Path,
    cache_prefix: Path,
    bin_s: float,
    rebuild_cache: bool,
) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray, Path, Path]:
    summary_path, per_core_path = cache_paths(cache_prefix)
    if rebuild_cache or not summary_path.exists() or not per_core_path.exists():
        summary_path, per_core_path = build_cpu_core_cache(raw_path, cache_prefix, bin_s)

    times: list[float] = []
    mean_util: list[float] = []
    p90_util: list[float] = []
    max_util: list[float] = []
    with summary_path.open(newline="") as handle:
        reader = csv.DictReader(handle)
        for row in reader:
            times.append(float(row["timestamp"]))
            mean_util.append(float(row["mean"]))
            p90_util.append(float(row["p90"]))
            max_util.append(float(row["max"]))
    return (
        np.array(times, dtype=float),
        np.array(mean_util, dtype=float),
        np.array(p90_util, dtype=float),
        np.array(max_util, dtype=float),
        summary_path,
        per_core_path,
    )


def smooth_series(times: np.ndarray, values: np.ndarray, window_s: float) -> np.ndarray:
    if window_s <= 0 or len(times) < 2:
        return values
    sample_interval_s = float(np.median(np.diff(times)))
    if sample_interval_s <= 0:
        return values
    window = max(1, int(round(window_s / sample_interval_s)))
    if window % 2 == 0:
        window += 1
    kernel = np.ones(window, dtype=float) / window
    return np.convolve(values, kernel, mode="same")


def draw_phase_markers(ax: plt.Axes, phases: list[PhaseWindow]) -> None:
    colors = {"Rollout": "#2D4059", "Train": "#EA5455"}
    for phase in phases:
        color = colors.get(phase.name, "black")
        ax.axvline(phase.start, color=color, linestyle="--", linewidth=1.0, alpha=0.9)
        ax.axvline(phase.end, color=color, linestyle="--", linewidth=1.0, alpha=0.9)
        ax.text(
            phase.start + (phase.end - phase.start) / 2,
            104,
            phase.name,
            ha="center",
            va="bottom",
            fontsize=13,
            color=color,
        )


def set_wallclock_axis(
    ax: plt.Axes,
    x_start: datetime,
    x_end: datetime,
    x_pad_s: float,
) -> None:
    x_pad = timedelta(seconds=x_pad_s)
    ax.set_xlim(x_start - x_pad, x_end + x_pad)
    ax.xaxis.set_major_locator(mdates.MinuteLocator(interval=5))
    ax.xaxis.set_major_formatter(mdates.DateFormatter("%H:%M"))
    ax.tick_params(axis="both", which="both", length=0)


def plot_cpu_core_util(
    times: np.ndarray,
    mean_util: np.ndarray,
    p90_util: np.ndarray,
    max_util: np.ndarray,
    phases: list[PhaseWindow],
    output_prefix: Path,
    smooth_window_s: float,
    x_pad_s: float,
) -> None:
    plt.rcParams.update(
        {
            "font.family": "Arial",
            "font.size": 12,
            "axes.linewidth": 1.0,
            "pdf.fonttype": 42,
            "ps.fonttype": 42,
        }
    )

    x_values = np.array([datetime.fromtimestamp(float(timestamp)) for timestamp in times])
    mean_smooth = smooth_series(times, mean_util, smooth_window_s)

    fig, ax = plt.subplots(figsize=(4, 2))
    line_width = 1.0
    ax.plot(
        x_values,
        mean_smooth,
        color="#2D4059",
        linewidth=line_width,
        alpha=0.95,
        label="Mean",
        zorder=5,
    )

    draw_phase_markers(ax, phases)
    ax.set_ylim(0, 110)
    ax.set_ylabel("CPU Util. (%)")
    # ax.set_xlabel("Wall-clock Time")
    ax.grid(axis="y", linestyle="--", linewidth=0.5, color="gray", alpha=0.55)
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)
    legend = ax.legend(
        ncol=1,
        fontsize=8,
        handletextpad=0.35,
        handlelength=1.2,
        labelspacing=0.2,
        loc="upper left",
        frameon=True,
    )
    legend.get_frame().set_edgecolor("black")
    legend.get_frame().set_linewidth(0.6)
    set_wallclock_axis(ax, x_values[0], x_values[-1], x_pad_s)
    fig.autofmt_xdate(rotation=0)
    fig.tight_layout()

    output_prefix.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(output_prefix.with_suffix(".pdf"), bbox_inches="tight")
    fig.savefig(output_prefix.with_suffix(".png"), dpi=240, bbox_inches="tight")
    plt.close(fig)


def read_per_core_matrix(
    per_core_path: Path,
) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    times: list[float] = []
    cores: list[int] = []
    values: dict[tuple[float, int], float] = {}
    with per_core_path.open(newline="") as handle:
        reader = csv.DictReader(handle)
        for row in reader:
            timestamp = float(row["timestamp"])
            core = int(row["cpu"])
            times.append(timestamp)
            cores.append(core)
            values[(timestamp, core)] = float(row["active_pct"])

    ordered_times = np.array(sorted(set(times)), dtype=float)
    ordered_cores = np.array(sorted(set(cores)), dtype=int)
    time_to_idx = {timestamp: idx for idx, timestamp in enumerate(ordered_times)}
    core_to_idx = {core: idx for idx, core in enumerate(ordered_cores)}
    matrix = np.full((len(ordered_cores), len(ordered_times)), np.nan)
    for (timestamp, core), active_pct in values.items():
        matrix[core_to_idx[core], time_to_idx[timestamp]] = active_pct
    return ordered_times, ordered_cores, matrix


def plot_cpu_core_heatmap(
    per_core_path: Path,
    phases: list[PhaseWindow],
    output_prefix: Path,
    x_pad_s: float,
) -> None:
    times, cores, matrix = read_per_core_matrix(per_core_path)
    x_values = np.array([datetime.fromtimestamp(float(timestamp)) for timestamp in times])
    extent = [
        mdates.date2num(x_values[0]),
        mdates.date2num(x_values[-1]),
        float(cores[0]) - 0.5,
        float(cores[-1]) + 0.5,
    ]

    plt.rcParams.update(
        {
            "font.family": "Arial",
            "font.size": 12,
            "axes.linewidth": 1.0,
            "pdf.fonttype": 42,
            "ps.fonttype": 42,
        }
    )
    fig, ax = plt.subplots(figsize=(4, 1.5))
    image = ax.imshow(
        matrix,
        aspect="auto",
        origin="lower",
        extent=extent,
        cmap="YlOrRd",
        vmin=0,
        vmax=100,
        interpolation="nearest",
        zorder=1,
    )
    draw_phase_markers(ax, phases)
    ax.set_ylim(float(cores[0]) - 0.5, float(cores[-1]) + 0.5)
    ax.set_ylabel("CPU Core")
    ax.set_xlabel("Wall-clock Time")
    set_wallclock_axis(ax, x_values[0], x_values[-1], x_pad_s)
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)
    colorbar = fig.colorbar(image, ax=ax, pad=0.02, fraction=0.055)
    colorbar.set_label("Util. (%)")
    colorbar.ax.tick_params(length=0)
    fig.autofmt_xdate(rotation=0)
    fig.tight_layout()

    heatmap_prefix = output_prefix.with_name(output_prefix.name + "_heatmap")
    fig.savefig(heatmap_prefix.with_suffix(".pdf"), bbox_inches="tight")
    fig.savefig(heatmap_prefix.with_suffix(".png"), dpi=240, bbox_inches="tight")
    plt.close(fig)


def resolve_phases(
    run_dir: Path,
    phase_csv: Path | None,
    times: np.ndarray,
    p90_util: np.ndarray,
) -> list[PhaseWindow]:
    if phase_csv is None:
        phase_csv = find_default_phase_csv(run_dir)
    if phase_csv is not None and phase_csv.exists():
        return read_phase_csv(phase_csv)

    rollout = read_rollout_window(run_dir)
    train = infer_train_window(
        times,
        p90_util,
        rollout_end=rollout.end,
        training_seconds=read_actor_training_seconds(run_dir / "train.log"),
    )
    phases = [rollout]
    if train is not None:
        phases.append(train)
    return phases


def main() -> None:
    args = parse_args()
    run_dir = args.run_dir
    output_prefix = (
        args.output_prefix
        if args.output_prefix is not None
        else run_dir / "cpu" / "cpu_core_util_timeline"
    )
    cache_prefix = (
        args.cache_prefix
        if args.cache_prefix is not None
        else run_dir / "cpu" / f"cpu_core_util_agg_{args.bin_s:g}s"
    )

    times, mean_util, p90_util, max_util, summary_path, per_core_path = (
        read_cpu_core_series(
            run_dir / "cpu" / "worker_cpu_core_util.csv",
            cache_prefix,
            args.bin_s,
            args.rebuild_cache,
        )
    )
    phases = resolve_phases(run_dir, args.phase_csv, times, p90_util)

    plot_cpu_core_util(
        times,
        mean_util,
        p90_util,
        max_util,
        phases,
        output_prefix,
        smooth_window_s=args.smooth_window_s,
        x_pad_s=args.x_pad_s,
    )
    plot_cpu_core_heatmap(per_core_path, phases, output_prefix, x_pad_s=args.x_pad_s)
    print(f"Wrote {summary_path}")
    print(f"Wrote {per_core_path}")
    print(f"Wrote {output_prefix.with_suffix('.pdf')}")
    print(f"Wrote {output_prefix.with_suffix('.png')}")
    print(f"Wrote {output_prefix.with_name(output_prefix.name + '_heatmap').with_suffix('.pdf')}")
    print(f"Wrote {output_prefix.with_name(output_prefix.name + '_heatmap').with_suffix('.png')}")


if __name__ == "__main__":
    main()
